# Generated by Django 5.2.6 on 2025-09-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado_en',
        ),
    ]
